<a href="https://colab.research.google.com/gist/mrnobodygivesfuck/d544c79cfb62e31ecd9e035f9db91a8b/praticalsession-11thfeb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#create an Array using numpy [1,2,3,4,5,6]
import numpy as np
arr=np.array([1,2,4,3,5,6])
print(arr.reshape(1,6)) 
print(arr.reshape(3,2)) 
print(arr.reshape(2,3))


[[1 2 4 3 5 6]]
[[1 2]
 [4 3]
 [5 6]]
[[1 2 4]
 [3 5 6]]


In [ ]:
#scalar multiplication
array2=arr*5
print(array2)


[ 5 10 20 15 25 30]


In [ ]:
#addation
array3=(array2)+4 
print(array3)

[ 9 14 24 19 29 34]


In [ ]:
#reshape
array4=array3.reshape(2,3) 
print(array4)


[[ 9 14 24]
 [19 29 34]]


In [ ]:
#datatype
array4.dtype 

dtype('int64')

In [ ]:
#generate array using arange(0,6)
array5=np.arange(0,4) 
print(array5)

[0 1 2 3]


In [ ]:
array6=np.linspace(0,3,num=4) 
print(array6)

[0. 1. 2. 3.]


In [ ]:
arr=np.random.random_integers(0,5,10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  """Entry point for launching an IPython kernel.


In [ ]:
#book dataframe
import pandas as pd 
books=pd.Series([2,4,6,8,10,12],[['abc','def','ghi','jkl','mno','pqr']])
print(books)

abc     2
def     4
ghi     6
jkl     8
mno    10
pqr    12
dtype: int64


In [ ]:
df=pd.DataFrame(data=books) 
print(df)

      0
abc   2
def   4
ghi   6
jkl   8
mno  10
pqr  12


In [ ]:
array7=np.random.random_integers(5,10,(3,4))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 10 + 1) instead
  """Entry point for launching an IPython kernel.


In [ ]:
df=pd.DataFrame(array4)
print(df)


    0   1   2
0   9  14  24
1  19  29  34


In [ ]:
#Dataframe Using Series
#Genrate Name,Salary,Desgination series then Dataframe
name=['rajat','ram','lakhan'] 
name=pd.Series(name)
print(name)

0     rajat
1       ram
2    lakhan
dtype: object


In [ ]:
salary=pd.Series(['145678','156789','89999']);
print(salary)

0    145678
1    156789
2     89999
dtype: object


In [ ]:
Designation=pd.Series(['Developer','HR','CEO'])
details=pd.DataFrame([name,salary,Designation],index=['Name','Salary', 'Designation'])
print(details)

                     0       1       2
Name             rajat     ram  lakhan
Salary          145678  156789   89999
Designation  Developer      HR     CEO


In [ ]:
#Student Dataframe 
student={'name':['Rajat','Ram','Lakhan'],'age': ['20','19','22'],'Branch':['CSE','ECE','IT'],'SGPA': ['8.6','5.4','4.2']}
student2=pd.DataFrame(student)
print(student2) 

     name age Branch SGPA
0   Rajat  20    CSE  8.6
1     Ram  19    ECE  5.4
2  Lakhan  22     IT  4.2
